HomeServices/Controllers/CustomerDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer;
using DataAccessLayer.Models;
using HomeServices.Models;
namespace HomeServices.Controllers
{
    public class CustomerDashboardController : Controller
    {
        // GET: CustomerDashboard
        public ActionResult Dashboard()
        {
            ViewBag.Login = "Customer";
            return View();
        }


        public ActionResult ViewServices()
        {
            var result = Data.ServiceList();
            ViewBag.result = new SelectList(result);
            return View();
        }
        [HttpPost]
        public ActionResult ViewServiceProvider(string Service)
        {
            var Id = (UserInfoModel)Session["UserData"];
            var ServiceProviders = Data.SPList(Service,Id.Id);
            //ViewBag.result = Result;
            return View(ServiceProviders);
        }
        [HttpPost]
        public ActionResult PlaceOrder(ServiceProviderModel provider)
        {
            Data.PlaceOrder(provider);
            return RedirectToAction("MyOrders","CustomerDashboard");
        }
        public ActionResult MyOrders()
        {
            var Id = (UserInfoModel)Session["UserData"];
            var Result = Data.Order(Id.Id);
            //ViewBag.result = Result;
            ViewBag.Payment = (string)Session["Payment"];
            Session["Payment"] = null;
            return View(Result);
        }

        [HttpPost]
        public ActionResult ChangeStatus(int OrderId,string Status)
        {
            ViewBag.Payment = (string)Session["Payment"];
            Data.ChangeStatus(OrderId, Status);
            return RedirectToAction("MyOrders", "CustomerDashboard");
        }
        private int SetLogInInfo(string type) {
            if (type == "Customer") {
                ViewBag.Login = "Customer";
            }
            return 1;
        }
    }
}

HomeServices/Controllers/reviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer.Models;
using DataAccessLayer;
namespace HomeServices.Controllers
{
    public class reviewController : Controller
    {
        // GET: review
        public ActionResult Index(int OrderId)
        {
            Session["orderid"] = OrderId;
            return View();
        }
        [HttpPost]
        public ActionResult Index(reviewmodel model)
        {
            int orderid = int.Parse(Session["orderid"].ToString());
            if(ModelState.IsValid)
            {
                Data.AddReview(model,orderid);
                return RedirectToAction("MyOrders","CustomerDashboard");
            }
            return View();
        }
    }
}

HomeServices/Views/CustomerDashboard/Dashboard.cshtml
<div class="Dashboard">
    <h2>Customer Dashboard..</h2>
    <div class="a"><a href="../CustomerDashboard/ViewServices">Place Order</a></div>
    <div class="a"><a href="../CustomerDashboard/MyOrders">Previous Order</a></div>
    <div class="a"><a href="~/Profile/ViewProfile">My Profile</a></div>
</div>
<h3>v @ViewBag.Login</h3>
<script>
    LogInInfo = ("@ViewBag.Login");
</script>

HomeServices/Views/CustomerDashboard/MyOrders.cshtml
@model List<DataAccessLayer.Models.OrderData>

@{ ViewBag.Title = "My Orders";}
@{
    var Placed = 0;
    var Accepted = 0;
    var Cancelled = 0;
    foreach (var i in Model) {
        if (i.status == "Active") {
            Placed++;
        }
        else if (i.status == "Completed" || i.status == "Declined") {
            Cancelled++;
        }
        else if (i.status == "Accepted" || i.status == "Served") {
            Accepted++;
        }


    }
}
<div class="CustomerList">

    <h3>Orders Placed</h3>
    @if (Placed == 0) {
        <h2>No Orders Yet...</h2>
    }
    else {
        <table class="CustomerList_Table">
            <tr>
                <th>
                    Order ID
                </th>
                <th>
                    Ordered By
                </th>
                <th>
                    WorkDone By
                </th>
                <th>
                    Status
                </th>
                <th>
                    Ordered Date
                </th>
                <th>
                    Scheduled Date
                </th>
                <th>
                    Price
                </th>
                <th colspan="2">
                    Action
                </th>
            </tr>
            @foreach (var i in Model) {
                if (i.status == "Active") {
                    <tr>
                        <td>
                            @i.id
                        </td>
                        <td>
                            @i.fromid
                        </td>
                        <td>
                            @i.toid
                        </td>
                        <td>
                            @i.status
                        </td>
                        <td>
                            @i.ordereddate
                        </td>
                        <td>
                            @i.scheduleddate
                        </td>
                        <td>
                            @i.price
                        </td>
                        <td>
                            @using (Html.BeginForm("ChangeStatus", "CustomerDashboard", FormMethod.Post)) {
                                <input type="hidden" name="OrderId" value=@i.id />
                                <input type="hidden" name="Status" value="Order Cancelled" />

                                <input type="submit" value="Cancel" />
                            }
                        </td>
                    </tr>
                }

            }
        </table>
    }<br />
    <br />
    <h3>Accepted Orders and Server Orders</h3>
    @if (Accepted == 0) {
        <h2>No Orders Yet...</h2>
    }
    else {
<table class="CustomerList_Table">
    <tr>
        <th>
            Order ID
        </th>
        <th>
            Ordered By
        </th>
        <th>
            WorkDone By
        </th>
        <th>
            Status
        </th>
        <th>
            Ordered Date
        </th>
        <th>
            Scheduled Date
        </th>
        <th>
            Price
        </th>
        <th colspan="2">
            Action
        </th>
    </tr>
    @foreach (var i in Model) {
        if (i.status == "Accepted" || i.status == "Served") {
            <tr>
                <td>
                    @i.id
                </td>
                <td>
                    @i.fromid
                </td>
                <td>
                    @i.toid
                </td>
                <td>
                    @i.status
                </td>
                <td>
                    @i.ordereddate
                </td>
                <td>
                    @i.scheduleddate
                </td>
                <td>
                    @i.price
                </td>
                <td>
                    @if (i.status == "Accepted") {
                        using (Html.BeginForm("ChangeStatus", "CustomerDashboard", FormMethod.Post)) {
                            <input type="hidden" name="OrderId" value=@i.id />
                            <input type="hidden" name="Status" value="Cancel" />

                            <input type="submit" value="Cancel" />
                        }

                    }
                    else if (i.status == "Served") {
                        using (Html.BeginForm("Pay", "Payment", FormMethod.Get)) {
                            <input type="hidden" name="OrderId" value=@i.id />

                            <input type="submit" value="Pay" />
                        }
                    }
                </td>
            </tr>
        }

    }
</table>
    }
    <br />
    <br />
    <h3>Completed Orders and Cancelled Orders</h3>
    @if (Cancelled == 0) {
        <h2>No Orders Yet...</h2>
    }
    else {
<table class="CustomerList_Table">
    <tr>
        <th>
            Order ID
        </th>
        <th>
            Ordered By
        </th>
        <th>
            WorkDone By
        </th>
        <th>
            Status
        </th>
        <th>
            Ordered Date
        </th>
        <th>
            Scheduled Date
        </th>
        <th>
            Price
        </th>
        <th colspan="2">
            Action
        </th>
    </tr>
    @foreach (var i in Model) {
        if (i.status == "Completed" || i.status == "Declined") {
            <tr>
                <td>
                    @i.id
                </td>
                <td>
                    @i.fromid
                </td>
                <td>
                    @i.toid
                </td>
                <td>
                    @i.status
                </td>
                <td>
                    @i.ordereddate
                </td>
                <td>
                    @i.scheduleddate
                </td>
                <td>
                    @i.price
                </td>
                <td>
                    @using (Html.BeginForm("Index", "review", FormMethod.Get)) {
                        <input type="hidden" name="OrderId" value=@i.id />


                        <input type="submit" value="Add Review" />
                    }
                </td>
            </tr>
        }

    }
</table>
    }
    <script>
    @Html.Raw(ViewBag.Payment)
    </script>

</div>

HomeServices/Views/CustomerDashboard/PlaceOrder.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PlaceOrder</title>
</head>
<body>
    @using (Html.BeginForm("ServiceProvider", "CustomerDashboard", FormMethod.Post))
    {
        @Html.DropDownList("services", (SelectList)ViewBag.result)
        <input type="submit" value="Select" />
    }
</body>
</html>

HomeServices/Views/CustomerDashboard/ViewServiceProvider.cshtml
@model List<DataAccessLayer.Models.ServiceProviderModel>
@{ ViewBag.Title = "List of Service Providers";}
    <div class="CustomerList">
        <h2>Select the Service Provider You want to Place the order</h2>
        <table class="CustomerList_Table">
            <tr>
                <th>
                    SP ID
                </th>
                <th>
                    SP Name
                </th>
                <th>
                    Rating
                </th>
                <th>
                    Schedule Date
                </th>
                <th>
                    Price
                </th>
                <th colspan="2">
                    Action
                </th>
            </tr>
            @foreach (var i in Model) {
                <tr>
                    <td>
                        @i.ServiceProviderId
                    </td>
                    <td>
                        @i.ServiceProviderName
                    </td>
                    <td>
                       
                        @i.Rating
                    </td>
                    @using (Html.BeginForm("PlaceOrder", "CustomerDashboard", FormMethod.Post)) {
                        <td>
                            <input type="datetime-local" name="ScheduledDate" required />
                        </td>
                        <td>
                            <input type="text" readonly value=@i.Price name="Price" />
                        </td>
                        <td>
                            <input type="hidden" name="CustomerId" value=@i.CustomerId />
                            <input type="hidden" name="ServiceProviderId" value=@i.ServiceProviderId />

                            <input type="submit" value="Place Order" />
                        </td>

                    }

                    @*@using (Html.BeginForm("PlaceOrder","CustomerDashboard",FormMethod.Post))
                    {
                        <td><input type="datetime-local" name="ScheduleDate" /></td>
                        <td><input type="hidden" name="ServiceProviderId" value="@i.ServiceProviderId" /></td>
                        <td><input type="submit" value="Place Order" /></td>

                    }*@

                </tr>
            }
        </table>

    </div>

HomeServices/Views/CustomerDashboard/ViewServices.cshtml
@{ 
    ViewBag.Title = "Select Service";
}
    <div>
        <h2>Select the service you need</h2>
        @using (Html.BeginForm("ViewServiceProvider", "CustomerDashboard", FormMethod.Post)) {
            @Html.DropDownList("Service", (SelectList)ViewBag.result)
            <input type="submit" value="Select" />
        }
    </div>