HomeServices/Controllers/ProviderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer.Models;
using DataAccessLayer;

namespace HomeServices.Controllers
{
    public class ProviderController : Controller
    {
        // GET: Provider
        public ActionResult Dashboard()
        {
            return View();
        }
        public ActionResult ReceivedOrder()
        {
            var User = (UserInfoModel)Session["UserData"];
            var res = Data.ServiceProvider(User.Id);
            return View(res);
        }

        [HttpPost]
        public ActionResult ReceivedOrder(int OrderId, string Status)
        {
            Data.ChangeStatus(OrderId, Status);
            return Redirect("~/Provider/ReceivedOrder/");
        }

        public ActionResult Previousorder()
        {
            var User = (UserInfoModel)Session["UserData"];
            var res = Data.ServiceProvider(User.Id);
            return View(res);

        }
    }
}

HomeServices/Views/Provider/Dashboard.cshtml

<div class="Dashboard">
    <h2>Service Provider Dasboard</h2>
    <div class="a"><a href="~/Provider/Receivedorder">Received Order</a></div>
    <div class="a"><a href="~/Provider/PreviousOrder">Previous Order</a></div>
    <div class="a"><a href="~/Profile/ViewProfile">My Profile</a></div>
</div>

HomeServices/Views/Provider/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


HomeServices/Views/Provider/Previousorder.cshtml
@model List<DataAccessLayer.Models.ListOrder>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Received Orders</title>
</head>
<body>
    @using (Html.BeginForm("Previousorder", "Provider", FormMethod.Post))
    {
        <table border="1">
            <tr>
                <td>
                    ID
                </td>
                <td>
                    Customer
                </td>
                <td>
                    Status
                </td>
                <td>
                    Status
                </td>
                <td>
                    Date
                </td>
                <td>
                    Shedule Date
                </td>
            </tr>
            @foreach (var r in Model)
            {
                <tr>
                    <td>
                        @r.Id
                    </td>
                    <td>
                        @r.FromFK
                    </td>
                    <td>
                        @r.Status
                    </td>
                    <td>
                        @r.Date
                    </td>
                    <td>
                        @r.ScheduleDate
                    </td>
                </tr>
            }
        </table>}
</body>
</html>

HomeServices/Views/Provider/Receivedorder.cshtml
@model List<DataAccessLayer.Models.ListOrder>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Received Orders</title>
</head>
<body>
        <table border="1">
            <tr>
                <td>
                    ID
                </td>
                <td>
                    Customer
                </td>
                <td>
                    Status
                </td>
                <td>
                    Date
                </td>
                <td>
                    Shedule Date
                </td>
                <td>
                    Action
                </td>
            </tr>
            @foreach (var r in Model)
            {
            <tr>
                <td>
                    @r.Id
                </td>
                <td>
                    @r.FromFK
                </td>
                <td>
                    @r.Status
                </td>
                <td>
                    @r.Date
                </td>
                <td>
                    @r.ScheduleDate
                </td>

                <td>
                    @if (r.Status == "Active")
                    {
                        using (Html.BeginForm("ReceivedOrder", "Provider", FormMethod.Post))
                        {
                            @Html.Hidden("OrderId", r.Id)
                            @Html.Hidden("Status", "Accepted")
                            <input type="submit" value="Accept" />
                        }

                        using (Html.BeginForm("ReceivedOrder", "Provider", FormMethod.Post))
                        {
                            @Html.Hidden("OrderId", r.Id)
                            @Html.Hidden("Status", "Declined")
                            <input type="submit" value="Decline" />
                        }

                    }  @if (r.Status == "Accepted")
                    {
                        using (Html.BeginForm("ReceivedOrder", "Provider", FormMethod.Post))
                        {
                            @Html.Hidden("OrderId", r.Id)
                            @Html.Hidden("Status", "Served")
                            <input type="submit" value="Served" />
                        }
                    }
                </td>
                </tr>
            }
        </table>
</body>
</html>